[/Script/TrackingAutoSetup.TrackingAutoSetupSubsystem]
; Default connection settings
DefaultProtocol=FreeD
DefaultIPAddress=127.0.0.1
DefaultFreeDPort=40000
DefaultOpenTrackSourceNumber=1
DefaultSubjectName=Camera

; Default camera settings
bCreateAnchorPoint=true
bAutoGenerateLensFile=true
bEnableVirtualCamera=false
